import React from 'react';
import { BankTransaction, BankAccount } from './types';
import { BuildingLibraryIcon } from '../../constants/icons';

export const mockBankTransactions: BankTransaction[] = [
    // === Compte Pro Inqom (acc_inqom) ===
    {
        id: 'tx_inqom_1',
        accountId: 'acc_inqom',
        description: 'Virement entrant - Client Alpha',
        date: '2026-03-28',
        amount: 4500.00,
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    {
        id: 'tx_inqom_2',
        accountId: 'acc_inqom',
        description: 'Paiement CB - Amazon AWS',
        date: '2026-03-27',
        amount: -120.50,
        status: 'À justifier',
        paymentMethod: 'Carte Pro',
    },
    {
        id: 'tx_inqom_3',
        accountId: 'acc_inqom',
        description: 'Virement sortant - Fournisseur XYZ',
        date: '2026-03-25',
        amount: -850.00,
        status: 'Justifié',
        paymentMethod: 'Virement',
    },
    // === Compte Pro SG (acc_1) - Total 30 transactions ===
    { 
        id: 'tx_acc1_1',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Beta Industries',
        date: '2025-07-29', 
        amount: 3500.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_2',
        accountId: 'acc_1',
        description: 'Paiement CB - Restaurant Le Gourmet',
        date: '2025-07-27', 
        amount: -150.50, 
        status: 'À justifier',
        paymentMethod: 'Carte Pro **** 1234',
    },
    { 
        id: 'tx_acc1_3',
        accountId: 'acc_1',
        description: 'Prélèvement - Assurance Pro MAAF',
        date: '2025-07-25', 
        amount: -320.00, 
        status: 'Justifié',
        paymentMethod: 'Prélèvement SEPA',
    },
    { 
        id: 'tx_acc1_4',
        accountId: 'acc_1',
        description: 'Paiement Fournisseur - Office Depot',
        date: '2025-07-24', 
        amount: -180.25, 
        status: 'À justifier',
        paymentMethod: 'Virement',
    },
    { 
        id: 'tx_acc1_5',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Gamma Services',
        date: '2025-07-23', 
        amount: 8500.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_6',
        accountId: 'acc_1',
        description: 'Paiement CB - Carburant TOTAL',
        date: '2025-07-21', 
        amount: -95.60, 
        status: 'À justifier',
        paymentMethod: 'Carte Pro **** 5678',
    },
    { 
        id: 'tx_acc1_7',
        accountId: 'acc_1',
        description: 'Prélèvement - Loyer Bureau',
        date: '2025-07-20', 
        amount: -2500.00, 
        status: 'Justifié',
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc1_8',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Delta Solutions',
        date: '2025-07-19', 
        amount: 1500.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_9',
        accountId: 'acc_1',
        description: 'Paiement Fournisseur - Adobe CC',
        date: '2025-07-18', 
        amount: -59.99, 
        status: 'Justifié',
        paymentMethod: 'Carte Pro **** 1234',
    },
    { 
        id: 'tx_acc1_10',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Epsilon Tech',
        date: '2025-07-17', 
        amount: 4200.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_11',
        accountId: 'acc_1',
        description: 'Paiement CB - Billet de train SNCF',
        date: '2025-07-16', 
        amount: -210.00, 
        status: 'À justifier',
        paymentMethod: 'Carte Pro **** 5678',
    },
    { 
        id: 'tx_acc1_12',
        accountId: 'acc_1',
        description: 'Prélèvement - Orange Pro',
        date: '2025-07-15', 
        amount: -110.40, 
        status: 'Justifié',
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc1_13',
        accountId: 'acc_1',
        description: 'Paiement Fournisseur - Amazon Web Services',
        date: '2025-07-14', 
        amount: -450.80, 
        status: 'Justifié',
        paymentMethod: 'Carte Pro **** 1234',
    },
    { 
        id: 'tx_acc1_14',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Zeta Corp',
        date: '2025-07-13', 
        amount: 980.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_15',
        accountId: 'acc_1',
        description: 'Paiement CB - Péage Autoroute',
        date: '2025-07-12', 
        amount: -35.20, 
        status: 'À justifier',
        paymentMethod: 'Carte Pro **** 5678',
    },
    { 
        id: 'tx_acc1_16',
        accountId: 'acc_1',
        description: 'Prélèvement - Impôts Gouv',
        date: '2025-07-10', 
        amount: -5200.00, 
        status: 'Justifié',
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc1_17',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Omega SARL',
        date: '2025-07-09', 
        amount: 6700.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_18',
        accountId: 'acc_1',
        description: 'Paiement Fournisseur - Google Workspace',
        date: '2025-07-08', 
        amount: -45.00, 
        status: 'Justifié',
        paymentMethod: 'Carte Pro **** 1234',
    },
    { 
        id: 'tx_acc1_19',
        accountId: 'acc_1',
        description: 'Paiement CB - Dîner client',
        date: '2025-07-07', 
        amount: -280.00, 
        status: 'À justifier',
        paymentMethod: 'Carte Pro **** 5678',
    },
    { 
        id: 'tx_acc1_20',
        accountId: 'acc_1',
        description: 'Prélèvement - Mutuelle Alan',
        date: '2025-07-05', 
        amount: -420.00, 
        status: 'Justifié',
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc1_21',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Kappa Co.',
        date: '2025-07-04', 
        amount: 2100.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_22',
        accountId: 'acc_1',
        description: 'Paiement Fournisseur - Prestataire Web',
        date: '2025-07-03', 
        amount: -1500.00, 
        status: 'À justifier',
        paymentMethod: 'Virement',
    },
    { 
        id: 'tx_acc1_23',
        accountId: 'acc_1',
        description: 'Paiement CB - Parking aéroport',
        date: '2025-07-02', 
        amount: -75.00, 
        status: 'À justifier',
        paymentMethod: 'Carte Pro **** 1234',
    },
    { 
        id: 'tx_acc1_24',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Lambda Group',
        date: '2025-07-01', 
        amount: 5500.00, 
        status: 'Justifié',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx_acc1_25',
        accountId: 'acc_1',
        description: 'Virement Salaires - Juin 2025',
        date: '2025-06-30', 
        amount: -24500.00, 
        status: 'Justifié',
        paymentMethod: 'Virement groupé',
    },
    { 
        id: 'tx_acc1_26',
        accountId: 'acc_1',
        description: 'Prélèvement URSSAF - Juin',
        date: '2025-06-25', 
        amount: -1830.00, 
        status: 'Justifié',
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx1',
        accountId: 'acc_1',
        description: 'Virement entrant - Client Alpha SARL',
        date: '2025-07-28', 
        amount: 12500.00, 
        status: 'Justifié', 
        analyticalCode: 'VENTE-SERV',
        attachmentRequired: false,
        needsReconciliation: true,
        reference: 'VIR-CLI-ALPHA-001',
        paymentMethod: 'Virement SEPA',
    },
    { 
        id: 'tx2',
        accountId: 'acc_1',
        description: 'Prélèvement URSSAF',
        date: '2025-07-25', 
        amount: -1850.75, 
        status: 'Justifié',
        attachmentRequired: true,
        needsReconciliation: false,
        reference: 'PRELEV-URSSAF-JUIL25',
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx3',
        accountId: 'acc_1',
        description: 'Paiement Fournisseur - Matériel Pro',
        date: '2025-07-22', 
        amount: -255.99, 
        status: 'À justifier', 
        analyticalCode: 'ACHAT-MAT',
        attachmentRequired: true,
        needsReconciliation: true,
        reference: 'CB-789123-MATPRO',
        paymentMethod: 'Carte Pro **** 5678',
    },
     { 
        id: 'tx7',
        accountId: 'acc_1',
        description: 'Virement Salaires - Juillet 2025',
        date: '2025-07-30', 
        amount: -25000.00, 
        status: 'Justifié',
        attachmentRequired: false,
        needsReconciliation: false,
        reference: 'SAL-JUIL2025',
        paymentMethod: 'Virement groupé',
    },

    // === Compte perso BNP (acc_2) - Total 10 transactions ===
    { 
        id: 'tx_acc2_1',
        accountId: 'acc_2',
        description: 'Paiement CB - Supermarché Monoprix',
        date: '2025-07-28', 
        amount: -85.40, 
        status: null,
        paymentMethod: 'Carte Perso **** 4321',
    },
    { 
        id: 'tx_acc2_2',
        accountId: 'acc_2',
        description: 'Virement permanent - Loyer perso',
        date: '2025-07-27', 
        amount: -950.00, 
        status: null,
        paymentMethod: 'Virement',
    },
    { 
        id: 'tx_acc2_3',
        accountId: 'acc_2',
        description: 'Retrait DAB BNP',
        date: '2025-07-26', 
        amount: -50.00, 
        status: null,
        paymentMethod: 'Espèces',
    },
    { 
        id: 'tx_acc2_4',
        accountId: 'acc_2',
        description: 'Paiement CB - Amazon.fr',
        date: '2025-07-25', 
        amount: -45.99, 
        status: null,
        paymentMethod: 'Carte Perso **** 4321',
    },
    { 
        id: 'tx_acc2_5',
        accountId: 'acc_2',
        description: 'Paiement CB - Restaurant Le Petit Zinc (déjeuner pro)',
        date: '2025-07-24', 
        amount: -35.50, 
        status: 'À justifier',
        paymentMethod: 'Carte Perso **** 4321',
    },
    { 
        id: 'tx_acc2_6',
        accountId: 'acc_2',
        description: 'Virement entrant - Salaire',
        date: '2025-07-23', 
        amount: 3500.00, 
        status: null,
        paymentMethod: 'Virement',
    },
    { 
        id: 'tx_acc2_7',
        accountId: 'acc_2',
        description: 'Prélèvement - Netflix',
        date: '2025-07-22', 
        amount: -13.49, 
        status: null,
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc2_8',
        accountId: 'acc_2',
        description: 'Paiement CB - Billet Cinéma',
        date: '2025-07-21', 
        amount: -24.00, 
        status: null,
        paymentMethod: 'Carte Perso **** 4321',
    },
    { 
        id: 'tx4',
        accountId: 'acc_2',
        description: 'Frais Prestation Web - Framer - Carte Perso XXXX', 
        date: '2025-07-20', 
        amount: -20.00, 
        status: 'À justifier', 
        attachmentRequired: true,
        needsReconciliation: false,
        reference: 'DEB-FRAMER-SUB-256',
        paymentMethod: 'Carte Perso **** 4321',
    },
    { 
        id: 'tx5',
        accountId: 'acc_2',
        description: 'Remboursement Note de frais - Voyage Lyon', 
        date: '2025-07-18', 
        amount: 245.50, 
        status: 'Justifié',
        attachmentRequired: true,
        needsReconciliation: false,
        reference: 'NDF-LYON-0725',
        paymentMethod: 'Virement',
    },
    
    // === Compte Perso 2 CA (acc_3) - Total 10 transactions ===
    { 
        id: 'tx_acc3_1',
        accountId: 'acc_3',
        description: 'Paiement CB - Boulangerie',
        date: '2025-07-28', 
        amount: -5.60, 
        status: null,
        paymentMethod: 'Carte Perso **** 8765',
    },
    { 
        id: 'tx_acc3_2',
        accountId: 'acc_3',
        description: 'Prélèvement - Spotify',
        date: '2025-07-26', 
        amount: -9.99, 
        status: null,
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc3_3',
        accountId: 'acc_3',
        description: 'Paiement CB - Déjeuner pro (La Cantine)',
        date: '2025-07-24', 
        amount: -22.50, 
        status: 'À justifier',
        paymentMethod: 'Carte Perso **** 8765',
    },
    { 
        id: 'tx_acc3_4',
        accountId: 'acc_3',
        description: 'Virement entrant - Vente Leboncoin',
        date: '2025-07-23', 
        amount: 75.00, 
        status: null,
        paymentMethod: 'Virement',
    },
    { 
        id: 'tx_acc3_5',
        accountId: 'acc_3',
        description: 'Paiement CB - Achat matériel bureau (FNAC)',
        date: '2025-07-22', 
        amount: -120.00, 
        status: 'À justifier',
        paymentMethod: 'Carte Perso **** 8765',
    },
    { 
        id: 'tx_acc3_6',
        accountId: 'acc_3',
        description: 'Retrait DAB CA',
        date: '2025-07-20', 
        amount: -20.00, 
        status: null,
        paymentMethod: 'Espèces',
    },
    { 
        id: 'tx_acc3_7',
        accountId: 'acc_3',
        description: 'Prélèvement - Free Mobile',
        date: '2025-07-18', 
        amount: -19.99, 
        status: null,
        paymentMethod: 'Prélèvement',
    },
    { 
        id: 'tx_acc3_8',
        accountId: 'acc_3',
        description: 'Paiement CB - Pharmacie',
        date: '2025-07-17', 
        amount: -15.80, 
        status: null,
        paymentMethod: 'Carte Perso **** 8765',
    },
    { 
        id: 'tx_acc3_9',
        accountId: 'acc_3',
        description: 'Virement entrant - Remboursement ami',
        date: '2025-07-16', 
        amount: 50.00, 
        status: null,
        paymentMethod: 'Virement',
    },
    { 
        id: 'tx6',
        accountId: 'acc_3',
        description: 'Paiement Fournisseur - Prestation Énergie', 
        date: '2025-07-15', 
        amount: -89.90, 
        status: 'À justifier', 
        analyticalCode: 'FRAIS-GEN',
        attachmentRequired: false,
        needsReconciliation: true,
        reference: 'FACT-ENERGIE-0725',
        paymentMethod: 'Virement',
    },
];

const BankPictogram1 = (props: React.SVGProps<SVGSVGElement>) => (
    React.createElement('div', { className: "w-10 h-10 flex items-center justify-center rounded-lg bg-teal-100" },
       React.createElement(BuildingLibraryIcon, { className: 'h-6 w-6 text-teal-700' })
    )
);

const BankPictogram2 = (props: React.SVGProps<SVGSVGElement>) => (
    React.createElement('div', { className: "w-10 h-10 flex items-center justify-center rounded-lg bg-sky-100" },
        React.createElement(BuildingLibraryIcon, { className: 'h-6 w-6 text-sky-700' })
    )
);

const BankPictogram3 = (props: React.SVGProps<SVGSVGElement>) => (
    React.createElement('div', { className: "w-10 h-10 flex items-center justify-center rounded-lg bg-indigo-100" },
       React.createElement(BuildingLibraryIcon, { className: 'h-6 w-6 text-indigo-700' })
    )
);

const BankPictogramInqom = (props: React.SVGProps<SVGSVGElement>) => (
    React.createElement('div', { className: "w-10 h-10 flex items-center justify-center rounded-lg bg-theme-primary-100" },
       React.createElement(BuildingLibraryIcon, { className: 'h-6 w-6 text-theme-primary-700' })
    )
);

export const mockBankAccounts: BankAccount[] = [
    {
        id: 'acc_inqom',
        accountName: 'Compte Pro Principal',
        bankName: 'Inqom',
        balance: 15730.45,
        iban: 'FR7699999001002606902389781',
        bic: 'SWNBFR22',
        status: 'Actif',
        logo: BankPictogramInqom,
        lastUpdated: new Date().toISOString(),
    },
    {
        id: 'acc_1',
        accountName: 'Compte Pro SG',
        bankName: 'Société Générale',
        balance: 60550,
        iban: 'FR7430003000407499387136B90',
        bic: 'SOGEFRPP',
        status: 'Actif',
        logo: BankPictogram1,
        lastUpdated: '2025-07-31T09:05:12Z',
    },
    {
        id: 'acc_2',
        accountName: 'Compte perso',
        bankName: 'BNP Paribas',
        balance: 1550,
        iban: 'FR0210096000501716876788W69',
        bic: 'BNPAFRPPXXX',
        status: 'Actif',
        logo: BankPictogram2,
        lastUpdated: '2025-07-31T09:05:12Z',
    },
    {
        id: 'acc_3',
        accountName: 'Compte Perso 2',
        bankName: 'Crédit Agricole',
        balance: 550,
        iban: 'FR9510096000403647464212F23',
        bic: 'AGRIFRPP861',
        status: 'Inactif',
        logo: BankPictogram3,
        lastUpdated: '2025-07-30T14:20:00Z',
    }
];